// Mocks generated by Mockito 5.4.6 from annotations
// in arebbus/test/widget/bus_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:arebbus/models/auth_response.dart' as _i2;
import 'package:arebbus/models/bus.dart' as _i5;
import 'package:arebbus/models/bus_response.dart' as _i4;
import 'package:arebbus/models/comment.dart' as _i3;
import 'package:arebbus/models/route.dart' as _i7;
import 'package:arebbus/models/route_response.dart' as _i8;
import 'package:arebbus/models/stop.dart' as _i6;
import 'package:arebbus/service/api_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComment_1 extends _i1.SmartFake implements _i3.Comment {
  _FakeComment_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBusResponse_2 extends _i1.SmartFake implements _i4.BusResponse {
  _FakeBusResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBus_3 extends _i1.SmartFake implements _i5.Bus {
  _FakeBus_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStop_4 extends _i1.SmartFake implements _i6.Stop {
  _FakeStop_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRoute_5 extends _i1.SmartFake implements _i7.Route {
  _FakeRoute_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRouteResponse_6 extends _i1.SmartFake implements _i8.RouteResponse {
  _FakeRouteResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i9.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> saveAuthData(_i2.AuthResponse? authResponse) =>
      (super.noSuchMethod(
            Invocation.method(#saveAuthData, [authResponse]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<_i2.AuthResponse?> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i10.Future<_i2.AuthResponse?>.value(),
          )
          as _i10.Future<_i2.AuthResponse?>);

  @override
  _i10.Future<bool> isLoggedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isLoggedIn, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i2.AuthResponse> loginUser(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [email, password]),
            returnValue: _i10.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#loginUser, [email, password]),
              ),
            ),
          )
          as _i10.Future<_i2.AuthResponse>);

  @override
  _i10.Future<_i2.AuthResponse> registerUser(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#registerUser, [name, email, password]),
            returnValue: _i10.Future<_i2.AuthResponse>.value(
              _FakeAuthResponse_0(
                this,
                Invocation.method(#registerUser, [name, email, password]),
              ),
            ),
          )
          as _i10.Future<_i2.AuthResponse>);

  @override
  _i10.Future<Map<String, dynamic>> fetchPosts(int? page, int? size) =>
      (super.noSuchMethod(
            Invocation.method(#fetchPosts, [page, size]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> createPost(
    String? content,
    List<String>? tags,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [content, tags]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<void> deletePost(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i3.Comment>> fetchCommentsForPost(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCommentsForPost, [postId]),
            returnValue: _i10.Future<List<_i3.Comment>>.value(<_i3.Comment>[]),
          )
          as _i10.Future<List<_i3.Comment>>);

  @override
  _i10.Future<_i3.Comment> createComment(int? postId, String? content) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [postId, content]),
            returnValue: _i10.Future<_i3.Comment>.value(
              _FakeComment_1(
                this,
                Invocation.method(#createComment, [postId, content]),
              ),
            ),
          )
          as _i10.Future<_i3.Comment>);

  @override
  _i10.Future<Map<String, dynamic>?> getPostById(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostById, [postId]),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<Map<String, dynamic>> togglePostUpvote(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#togglePostUpvote, [postId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> toggleCommentUpvote(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCommentUpvote, [commentId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  Map<String, dynamic> parseUpvoteResponse(
    Map<String, dynamic>? responseData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#parseUpvoteResponse, [responseData]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i10.Future<void> debugPrintStoredAuth() =>
      (super.noSuchMethod(
            Invocation.method(#debugPrintStoredAuth, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> debugClearAllAuth() =>
      (super.noSuchMethod(
            Invocation.method(#debugClearAllAuth, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> debugPrintAllStoredKeys() =>
      (super.noSuchMethod(
            Invocation.method(#debugPrintAllStoredKeys, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i4.BusResponse> getAllBuses({int? page = 0, int? size = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllBuses, [], {#page: page, #size: size}),
            returnValue: _i10.Future<_i4.BusResponse>.value(
              _FakeBusResponse_2(
                this,
                Invocation.method(#getAllBuses, [], {#page: page, #size: size}),
              ),
            ),
          )
          as _i10.Future<_i4.BusResponse>);

  @override
  _i10.Future<_i4.BusResponse> getInstalledBuses({
    int? page = 0,
    int? size = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getInstalledBuses, [], {
              #page: page,
              #size: size,
            }),
            returnValue: _i10.Future<_i4.BusResponse>.value(
              _FakeBusResponse_2(
                this,
                Invocation.method(#getInstalledBuses, [], {
                  #page: page,
                  #size: size,
                }),
              ),
            ),
          )
          as _i10.Future<_i4.BusResponse>);

  @override
  _i10.Future<_i5.Bus> getBusById(int? busId) =>
      (super.noSuchMethod(
            Invocation.method(#getBusById, [busId]),
            returnValue: _i10.Future<_i5.Bus>.value(
              _FakeBus_3(this, Invocation.method(#getBusById, [busId])),
            ),
          )
          as _i10.Future<_i5.Bus>);

  @override
  _i10.Future<Map<String, dynamic>> installBus(int? busId) =>
      (super.noSuchMethod(
            Invocation.method(#installBus, [busId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> uninstallBus(int? busId) =>
      (super.noSuchMethod(
            Invocation.method(#uninstallBus, [busId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<_i6.Stop> getStopById(int? stopId) =>
      (super.noSuchMethod(
            Invocation.method(#getStopById, [stopId]),
            returnValue: _i10.Future<_i6.Stop>.value(
              _FakeStop_4(this, Invocation.method(#getStopById, [stopId])),
            ),
          )
          as _i10.Future<_i6.Stop>);

  @override
  _i10.Future<_i7.Route> getRouteById(int? routeId) =>
      (super.noSuchMethod(
            Invocation.method(#getRouteById, [routeId]),
            returnValue: _i10.Future<_i7.Route>.value(
              _FakeRoute_5(this, Invocation.method(#getRouteById, [routeId])),
            ),
          )
          as _i10.Future<_i7.Route>);

  @override
  _i10.Future<_i8.RouteResponse> getAllRoutes({
    int? page = 0,
    int? size = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutes, [], {#page: page, #size: size}),
            returnValue: _i10.Future<_i8.RouteResponse>.value(
              _FakeRouteResponse_6(
                this,
                Invocation.method(#getAllRoutes, [], {
                  #page: page,
                  #size: size,
                }),
              ),
            ),
          )
          as _i10.Future<_i8.RouteResponse>);

  @override
  _i10.Future<_i6.Stop> createStop({
    required String? name,
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createStop, [], {
              #name: name,
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i10.Future<_i6.Stop>.value(
              _FakeStop_4(
                this,
                Invocation.method(#createStop, [], {
                  #name: name,
                  #latitude: latitude,
                  #longitude: longitude,
                }),
              ),
            ),
          )
          as _i10.Future<_i6.Stop>);

  @override
  _i10.Future<_i7.Route> createRoute({
    required String? name,
    required List<int>? stopIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createRoute, [], {
              #name: name,
              #stopIds: stopIds,
            }),
            returnValue: _i10.Future<_i7.Route>.value(
              _FakeRoute_5(
                this,
                Invocation.method(#createRoute, [], {
                  #name: name,
                  #stopIds: stopIds,
                }),
              ),
            ),
          )
          as _i10.Future<_i7.Route>);

  @override
  _i10.Future<_i5.Bus> createBus({
    required String? name,
    required int? routeId,
    required int? capacity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createBus, [], {
              #name: name,
              #routeId: routeId,
              #capacity: capacity,
            }),
            returnValue: _i10.Future<_i5.Bus>.value(
              _FakeBus_3(
                this,
                Invocation.method(#createBus, [], {
                  #name: name,
                  #routeId: routeId,
                  #capacity: capacity,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.Bus>);

  @override
  _i10.Future<List<_i6.Stop>> getNearbyStops({
    required double? latitude,
    required double? longitude,
    double? radius = 3.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNearbyStops, [], {
              #latitude: latitude,
              #longitude: longitude,
              #radius: radius,
            }),
            returnValue: _i10.Future<List<_i6.Stop>>.value(<_i6.Stop>[]),
          )
          as _i10.Future<List<_i6.Stop>>);
}
